AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  allForm
  Sample SAM Template for allForm

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  SignUpFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: all-functions/signup
      Handler: signup.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: ap-south-1_fF3unWCgD
          COGNITO_CLIENT_ID: 4tvgqs3qvhtpr2tq796i746kln
          COGNITO_REGION: ap-south-1
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /signup
            Method: post

  OtpVerificationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: all-functions/otpverification
      Handler: otpVerification.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: ap-south-1_fF3unWCgD
          COGNITO_CLIENT_ID: 4tvgqs3qvhtpr2tq796i746kln
          COGNITO_REGION: ap-south-1
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /otpVerification
            Method: post

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: all-functions/login
      Handler: login.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: ap-south-1_fF3unWCgD
          COGNITO_CLIENT_ID: 4tvgqs3qvhtpr2tq796i746kln
          COGNITO_REGION: ap-south-1
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /login
            Method: post
